class TerjeRadiationConstants
{
	const float RADIATION_MAX_VALUE = 5;

	const int RADIATION_PLAYER_ACCUMULATOR_SERVER_MAX = 5000;
	const int RADIATION_PLAYER_ACCUMULATOR_SYNCH_MAX = 500;
	const float RADIATION_PLAYER_ACCUMULATOR_SYNCH_DIVIDER = 10;
	
	const int RADIATION_ITEMS_ACCUMULATOR_SERVER_MAX = 5000;
	const int RADIATION_ITEMS_ACCUMULATOR_SYNCH_MAX = 500;
	const float RADIATION_ITEMS_ACCUMULATOR_SYNCH_DIVIDER = 10;
	
	const int RADIATION_ANIMALS_ACCUMULATOR_SERVER_MAX = 5000;
	const int RADIATION_ANIMALS_ACCUMULATOR_SYNCH_MAX = 500;
	const float RADIATION_ANIMALS_ACCUMULATOR_SYNCH_DIVIDER = 10;
	const float RADIATION_ANIMALS_DAMAGE_THRESHOLD = 1000;
	const float RADIATION_ANIMALS_DAMAGE_PER_SEC = 1;
	
	const int RADIATION_ZOMBIE_ACCUMULATOR_SERVER_MAX = 5000;
	const int RADIATION_ZOMBIE_ACCUMULATOR_SYNCH_MAX = 500;
	const float RADIATION_ZOMBIE_ACCUMULATOR_SYNCH_DIVIDER = 10;
	const float RADIATION_ZOMBIE_DAMAGE_THRESHOLD = 1000;
	const float RADIATION_ZOMBIE_DAMAGE_PER_SEC = 1;
	
	const int RADIATION_VEHICLE_ACCUMULATOR_SERVER_MAX = 5000;
	const int RADIATION_VEHICLE_ACCUMULATOR_SYNCH_MAX = 500;
	const float RADIATION_VEHICLE_ACCUMULATOR_SYNCH_DIVIDER = 10;
}